---
deployment:
  tasks:
    - /bin/cp index.html /home/abongsha/ourgoods.bongshai.com/
    - /bin/cp .htaccess /home/abongsha/ourgoods.bongshai.com/ || true
    - /bin/cp -R assets /home/abongsha/ourgoods.bongshai.com/
    - /bin/cp -R images /home/abongsha/ourgoods.bongshai.com/ || true
    - /bin/cp favicon.svg /home/abongsha/ourgoods.bongshai.com/ || true
    - /bin/cp icons.svg /home/abongsha/ourgoods.bongshai.com/ || true
    - /bin/cp manifest.json /home/abongsha/ourgoods.bongshai.com/ || true
    - /bin/cp realProducts.json /home/abongsha/ourgoods.bongshai.com/ || true
